language: node_js
node_js:
  - 6
  - 8
  - stable
env:
  - CXX=g++-4.9
os:
  - linux
  - osx
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - gcc-4.9
       - g++-4.9
